# Generated by Django 2.2.2 on 2019-06-18 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190616_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 18, 8, 20, 4, 182929, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='avg_rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
