# Generated by Django 2.2.2 on 2019-06-18 20:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20190618_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 18, 20, 20, 21, 685734, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
        ),
    ]
