# Generated by Django 2.2.2 on 2019-06-19 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20190619_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 19, 15, 8, 50, 930967, tzinfo=utc)),
        ),
    ]
