# Generated by Django 2.2.2 on 2019-06-20 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20190619_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 13, 28, 44, 384712, tzinfo=utc)),
        ),
    ]
