# Generated by Django 2.2.2 on 2019-06-20 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20190620_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 19, 37, 9, 371807, tzinfo=utc)),
        ),
    ]
