# Generated by Django 2.2.2 on 2019-06-20 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20190621_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 20, 4, 51, 121672, tzinfo=utc)),
        ),
    ]
