# Generated by Django 2.2.2 on 2019-07-09 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20190621_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 7, 8, 49, 810810, tzinfo=utc)),
        ),
    ]
