# Generated by Django 2.2.2 on 2019-07-09 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20190709_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 9, 1, 4, 428749, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, default='download.png', upload_to='album-image'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, default='download.png', upload_to='artist-image'),
        ),
    ]
